### PR TITLE
Adds question about making numpy it's own independent project.

### PR DESCRIPTION
**Pull request by brianpmarks**
Hello @waywaaard. This pull request is just to start a discussion and hear your thoughts. 

I'm with https://trinket.io and work with @bzwheeler who added the ability to import external modules into skulpt. At Trinket we've had several users express an interest in using numpy in their classes. We'd love to be able to offer this to them. We discovered [http://waywaaard.github.io/skulpt/](your site) and wondered if you'd be interested in creating a separate "numpy.js" (and others like matplotlib) repo? Something similar to what we did with [https://github.com/trinketapp/pygal.js](pygal.js) is what we have in mind.

We are certainly willing to help make this happen as well as contributing updates as time allowed. Thanks very much for your thoughts!

### CODE REVIEW

**Comment by ebertmi** [comment]
Yeah, thanks for the request. That's on my long todo list. Though, I am little bit busy right now. Especially doing some cleanup and more testing is required and a more comprehensive list of what is supported and what not.

For matplotlib I need to refactor the whole jQuery stuff in order to use pure javascript calls. I am going to open a new repo in the next days and adding some more description.

**Comment by ebertmi** [comment]
I just created new repos for both modules:

https://github.com/waywaaard/skulpt_matplotlib
https://github.com/waywaaard/skulpt_numpy

I guess we should start with numpy first.

**Comment by brianpmarks** [comment]
That's awesome! Thanks for creating those. We're interested in using the numpy module right away.

Does numpy also depend your changes to skulpt's core math library? Or does it only rely on math.js?

**Comment by ebertmi** [comment]
Partially, at least the all trigonomeric functions like `sinh`, `cosh`, and the `dot` functions relies on it, though you can use it without it and an appropriate Python exception is thrown when you are trying to use them.

I am going to add an readme.

**Comment by ebertmi** [comment]
Added a readme to the new repo.

**Comment by brianpmarks** [comment]
Looks great! We've integrated this version into trinket. We haven't announced it widely as we're hoping to get some of our users trying it out first. Here's an early example created by a Physics teacher: https://trinket.io/python/f7a4520943

I expect we'll be getting requests to add routines that might not be there. Once that happens I'd love your thoughts and advice on incorporating them. Hopefully we'll be able to send some pull requests your way in the near future!

**Comment by ebertmi** [comment]
Glad to see, that it is already working. I am sure there a bunch of useful methods to implement, also there is a lot of work to do on the matplotlib library.

But I think the most valuable feature is the ndarray currently. But I am happy to help to implement more features and or review code.

**Pull request closed without merging**
